baseURL = "https://bonded.designbuildautomate.io"
languageCode = "en-us"
title = "Bonded Coffee Co"
disableKinds = ["taxonomy", "term", "RSS", "sitemap"]

[markup.goldmark.renderer]
  unsafe = true

[params]
  description = "Small-batch coffee roasted on our 14-acre farm in Lost River Valley, WV"
  author = "Bonded Coffee Co"
